services:
  cozybookstore:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./test-results:/app/test-results
      - ./coverage:/app/coverage
    ports:
      - "3001:3000"
    command: npm start